INSERT INTO CATEGORIA(ID, NOME)
	VALUES
		(NEWID(), 'INFORMÁTICA'),
		(NEWID(), 'ELETRÔNICOS'),
		(NEWID(), 'VESTUÁRIO'),
		(NEWID(), 'LIVRARIA'),
		(NEWID(), 'GAMES'),
		(NEWID(), 'CAMA, MESA E BANHO'),
		(NEWID(), 'OUTROS');
GO